version: '3'
services:
  
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1q2w3e4r
      - MONGO_INITDB_DATABASE=ChatDB
    volumes:
      - ./mongo_data:/etc/mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:27017"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
      
  mongo-dashboard:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1q2w3e4r
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  # web-service:
  #   build: .
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:6000"]
  #     interval: 1m30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s


