export const MESSAGE = {
	GET_MESSAGE:"GET_MESSAGE",
	MESSAGE_ERROR:"MESSAGE_ERROR",
	DELETE_MESSAGE:"DELETE_MESSAGE",
	SEND_MESSAGE:"SEND_MESSAGE",
}

export const ROOM = {
    JOIN_ROOM:"JOIN_ROOM",
    LEAVE_ROOM:"LEAVE_ROOM",
	GET_ROOM:"GET_ROOM"
}

export const USER ={
    LOGIN_USER:"LOGIN_USER"
}
